### ISSUE TITLE
error when doing /troll

### ISSUE THREAD

**Issue by rissoru1592** [TheJokerDev/TrollGUI#1]
[12:19:11 ERROR]: Could not pass event PlayerInteractEvent to TrollGUI v1.5
java.lang.NullPointerException: null
at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:356) ~[patched_1.13.2.jar:git-Paper-655]
at me.TheJokerDev.troll.messages.Files.getString(Files.java:38) ~[?:?]
at me.TheJokerDev.troll.listeners.TrollListeners.onPlayerInteractBlock(TrollListeners.java:991) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor377.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-655]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-655]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-655]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-655]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:320) ~[patched_1.13.2.jar:git-Paper-655]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:287) ~[patched_1.13.2.jar:git-Paper-655]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:283) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1386) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-655]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_242]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_242]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-655]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by rissoru1592** [comment]
sorry, not /troll, but when i click myself after i did /troll
